version: '3.8'

services:
  auth-service:
    build: ./auth_service
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://mongo-auth:27017/auth-service
      - JWT_SECRET=starportal_notification
    depends_on:
      - mongo-auth

  notification-service:
    build: ./notification_service
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo-notification:27017/notification-service
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - mongo-notification
      - kafka

  real-time-service:
    build: ./real_time_service
    ports:
      - "8080:8080"
    environment:
      - KAFKA_BROKER=kafka:9092
      - JWT_SECRET=starportal_notification
    depends_on:
      - kafka

  mongo-auth:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongo-auth-data:/data/db

  mongo-notification:
    image: mongo:latest
    ports:
      - "27019:27017"
    volumes:
      - mongo-notification-data:/data/db

  kafka:
    image: apache/kafka:3.7.1
    container_name: my-kafka-container  
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@localhost:9092
      KAFKA_CFG_LOG_DIRS: /var/lib/kafka/data
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_CFG_MIN_INSYNC_REPLICAS: 1
      KAFKA_CFG_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CFG_ZOOKEEPER_CONNECT: ""
      KAFKA_CFG_NO_ZOOKEEPER: "true"
    volumes:
      - kafka-data:/var/lib/kafka/data

volumes:
  mongo-auth-data:
  mongo-notification-data:
  kafka-data:
