version: '3.8'

services:
  auth-service:
    build: ./auth_service
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/auth-service
      - JWT_SECRET=starportal_notification
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
